version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db

  app:
    depends_on:
      - mongo
    build:
      context: '${GITHUB_WORKSPACE}'
      dockerfile: Dockerfile-ci
    # The app service's environmental variables.
    # Note: The environmental variables with prefix 'TEST_' are used when running tests.
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://root:password@mongo:27017/softwareRepository?authSource=admin
      TEST_MONGODB_URI: mongodb://root:password@mongo:27017/softwareRepositoryTest?authSource=admin
      FIREBASE_CLIENT_API_KEY: ${FIREBASE_CLIENT_API_KEY}
      # Your firebase service account information
      FIREBASE_ADMIN_SA_TYPE: ${FIREBASE_ADMIN_SA_TYPE}
      FIREBASE_ADMIN_SA_PROJECT_ID: ${FIREBASE_ADMIN_SA_PROJECT_ID}
      FIREBASE_ADMIN_SA_PRIVATE_KEY_ID: ${FIREBASE_ADMIN_SA_PRIVATE_KEY_ID}
      FIREBASE_ADMIN_SA_PRIVATE_KEY: ${FIREBASE_ADMIN_SA_PRIVATE_KEY}
      FIREBASE_ADMIN_SA_CLIENT_EMAIL: ${FIREBASE_ADMIN_SA_CLIENT_EMAIL}
      FIREBASE_ADMIN_SA_CLIENT_ID: ${FIREBASE_ADMIN_SA_CLIENT_ID}
      FIREBASE_ADMIN_SA_AUTH_URI: ${FIREBASE_ADMIN_SA_AUTH_URI}
      FIREBASE_ADMIN_SA_TOKEN_URI: ${FIREBASE_ADMIN_SA_TOKEN_URI}
      FIREBASE_ADMIN_SA_AUTH_PROVIDER_X509_CERT_URL: ${FIREBASE_ADMIN_SA_AUTH_PROVIDER_X509_CERT_URL}
      FIREBASE_ADMIN_SA_CLIENT_X509_CERT_URL: ${FIREBASE_ADMIN_SA_CLIENT_X509_CERT_URL}
    ports:
      - 8080:8080
    command: 'npm run test-ci'

volumes:
  db-data:
