PUT http://localhost:3001/api/software/5f997876dde20a5a60ce1c64
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsImlkIjoiNWY4ZGEzODcwODlmZmY0ZGIwNmJjMGFmIiwiaWF0IjoxNjAzODkzMzExfQ.ARy4EKDMzJqd4DcZyWXP5hygSQ9A2Bw1YfMQ-Nb03JU

{
    "description": "A sample software made by a happy person love",
    "homePage": "http://apple.com.sg",
    "platform": "MacOS",
    "meta": {
        "tags": ["hello", "world"],
        "votes": 1
    },
    "query": {
        "isEnabled": true
    },

    "isActiveDevelopment": true
}
