POST http://localhost:3001/api/softwares/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsImlkIjoiNWY2MjJmM2RjYzI5MWE4M2M0NTYzYWE4IiwiaWF0IjoxNjAwMjcwMTQ1fQ._6cFNZ2MlkSjn6B8XeyS3ek5HZWnheeRh2BPE6slox0

{
    "name": "SampleSoftware8",
    "description": "A sample software",
    "homePage": "http://example.com",
    "platforms": [
        "Windows"
    ],
    "isActiveDevelopment": true
}