name: App Container CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 8

    steps:
      - name: checkout
        uses: actions/checkout@v2
      # Pull the latest image to build, and avoid caching pull-only images.
      # (docker pull is faster than caching in most cases.)
      - name: docker-compose pull
        run: docker-compose pull
      - name: docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: descrypt firebase secret
        run: ./.github/scripts/decrypt_firebase_secret.sh
        env:
          DECRYPTION_PASSPHRASE: ${{ secrets.DECRYPTION_PASSPHRASE }}
      - name: Run test in container
        shell: bash
        env:
          TEST_FIREBASE_CLIENT_API_KEY: ${{ secrets.TEST_FIREBASE_CLIENT_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ./.github/ci/firebase.gpg
        run: docker-compose --file ./.github/ci/docker-compose-test.yml up --build --exit-code-from app
